// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD70pSFEVpcJ6xNDIV3ERTCFPxITtGH_7I',
    appId: '1:301299794403:web:6bf0ec2e3fe027f75ca0d6',
    messagingSenderId: '301299794403',
    projectId: 'studysphere-8a327',
    authDomain: 'studysphere-8a327.firebaseapp.com',
    storageBucket: 'studysphere-8a327.firebasestorage.app',
    measurementId: 'G-L3YMBQD394',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpvTvtk3ae-aZPcqqQmbaBItMWqvXVFQE',
    appId: '1:301299794403:android:7d7c1225569f86ce5ca0d6',
    messagingSenderId: '301299794403',
    projectId: 'studysphere-8a327',
    storageBucket: 'studysphere-8a327.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkUQgLGQ-c70lcKdBq4vHbb5LCCFtfwa4',
    appId: '1:301299794403:ios:3440c9d948ced0e25ca0d6',
    messagingSenderId: '301299794403',
    projectId: 'studysphere-8a327',
    storageBucket: 'studysphere-8a327.firebasestorage.app',
    iosBundleId: 'com.example.studysphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkUQgLGQ-c70lcKdBq4vHbb5LCCFtfwa4',
    appId: '1:301299794403:ios:3440c9d948ced0e25ca0d6',
    messagingSenderId: '301299794403',
    projectId: 'studysphere-8a327',
    storageBucket: 'studysphere-8a327.firebasestorage.app',
    iosBundleId: 'com.example.studysphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD70pSFEVpcJ6xNDIV3ERTCFPxITtGH_7I',
    appId: '1:301299794403:web:761af0d48b96cdb85ca0d6',
    messagingSenderId: '301299794403',
    projectId: 'studysphere-8a327',
    authDomain: 'studysphere-8a327.firebaseapp.com',
    storageBucket: 'studysphere-8a327.firebasestorage.app',
    measurementId: 'G-0FY7TZN6ZS',
  );
}
